### PR TITLE
simulation enhancements

### LINKED ISSUE #1: Suggested visual and simulation enhancements.
The attached zip file contains some suggested visual and simulation enhancements.  This is slightly newer than the one I sent via chief delphi mail.  The following changes were made:
1) added color wheel visual (main)
2) added arm visual (main)
3) reversed color direction to correspond to wheel picture (sensor)
4) added some motor start/stop lag (sensor)
5) added some random wheel slip.
6) added some simulated starting friction for wheel and arm motors.
Do with this as you want....
[2020 Control Panel_JAS_R1.zip](https://github.com/superhornets/FRC-Simulations/files/4877131/2020.Control.Panel_JAS_R1.zip)

### PR DESCRIPTION
**Pull request by jsimpso81**
Added moving pictures for arm and control panel.  Added lag to wheel and arm.  Added starting friction to arm and control panel.  Added some slippage to control panel.  Added LabVIEW #NOTE bookmarks describing individual changes.

### CODE REVIEW

**Comment by jsimpso81** [comment]
Let me know if there is anything else I need to do.  I think this "pull" request is complete, but since it's my first one, I'm not quite certain.  Jim

**Comment by JonathanLindsey** [comment]
Sorry, I've been pretty busy recently.

Nice job! I just made a few tweaks and pushed my changes to your branch.

1. I intended part of the challenge to be making the indicator of the _Game Data_ if desired (true, it's not quite clear in my CD post that you may modify the Main VI for this purpose) so I removed the associated code.
2. I added a list of contributors in the Contributing.md file with your name and a concise description of your changes. I removed the `#Note` (thanks, those helped me find your changes) and your name from the in code comments. Also, you automatically get credit because of the git commit history.
3. I moved the EXE location under the Control Panel folder (perhaps just my personal preference) and turned off the EXE's automatic version incrementing (that's annoying because git sees it as a change when you've only built the EXE for yourself).

Let me know if I messed anything up accidentally. If not, I'll go ahead and merge.

Thanks!

**Comment by jsimpso81** [comment]
I only looked at briefly at the VI's, but it looked okay to me.  (I didn't take the time to copy the project and add my "Teleop.VI" to see if it moves.  (I used the LabVIEW visual compare via Tortise GIT to compare the VI files.) 

I did at two readme files, one for the repository and one for the LabVIEW project.  You might want to review and revise.

Let me know if I need to do anything else.  I assume if you are happy you will merge this back into your master, then this "fork" (or is it a branch..) can be deleted.

**Comment by jsimpso81** [comment]
PS -- No worries about being busy.  Retirement has some benefits.

**Comment by JonathanLindsey** [comment]
Nice! Thanks again!

**Pull request merged**
